/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2612__factory } from "./IERC2612__factory";
export { IERC2612Standalone__factory } from "./IERC2612Standalone__factory";
