/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IApprovalReceiver,
  IApprovalReceiverInterface,
} from "../../../../src/ERC20/ERC20Base.sol/IApprovalReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onTokenApproval",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IApprovalReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IApprovalReceiverInterface {
    return new utils.Interface(_abi) as IApprovalReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IApprovalReceiver {
    return new Contract(address, _abi, signerOrProvider) as IApprovalReceiver;
  }
}
