/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPaidForReceiver,
  IPaidForReceiverInterface,
} from "../../../../src/ERC20/ERC20Base.sol/IPaidForReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "forAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenPaidFor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPaidForReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IPaidForReceiverInterface {
    return new utils.Interface(_abi) as IPaidForReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPaidForReceiver {
    return new Contract(address, _abi, signerOrProvider) as IPaidForReceiver;
  }
}
