/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20BaseSol from "./ERC20Base.sol";
export type { erc20BaseSol };
export type { ERC20Internal } from "./ERC20Internal";
export type { SimpleERC20 } from "./SimpleERC20";
export type { WithPermit } from "./WithPermit";
export type { WithPermitAndFixedDomain } from "./WithPermitAndFixedDomain";
