/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20 from "./ERC20";
export * as greetingsRegistry from "./GreetingsRegistry";
export * as interfaces from "./Interfaces";
export * as libraries from "./Libraries";
export * as ticketMarketSol from "./TicketMarket.sol";
export { Event__factory } from "./Event__factory";
export { EventManager__factory } from "./EventManager__factory";
