/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as greetingsRegistry from "./GreetingsRegistry";
export type { greetingsRegistry };
import type * as interfaces from "./Interfaces";
export type { interfaces };
import type * as libraries from "./Libraries";
export type { libraries };
import type * as ticketMarketSol from "./TicketMarket.sol";
export type { ticketMarketSol };
export type { Event } from "./Event";
export type { EventManager } from "./EventManager";
