/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20BaseSol from "./ERC20Base.sol";
export { ERC20Internal__factory } from "./ERC20Internal__factory";
export { SimpleERC20__factory } from "./SimpleERC20__factory";
export { WithPermit__factory } from "./WithPermit__factory";
export { WithPermitAndFixedDomain__factory } from "./WithPermitAndFixedDomain__factory";
