/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Base } from "./ERC20Base";
export type { IApprovalReceiver } from "./IApprovalReceiver";
export type { IPaidForReceiver } from "./IPaidForReceiver";
export type { ITransferReceiver } from "./ITransferReceiver";
